# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Document',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
